### ISSUE TITLE
Not upgraded to WebSocket

### ISSUE THREAD

**Issue by marianoarga** [kkazuo/dart-wamp-client#1]
I get this error when trying to connect to a socket.io server from a Flutter app.
`WebSocketException: Connection to '..' was not upgraded to websocket`

I get this library from "Flutter" section of dart libraries.

**Comment by kkazuo** [comment]
This library is [WAMP](https://wamp-proto.org) protocol client.
I don't know any relationship with socket.io.
Thanks
