### ISSUE TITLE
onDisconnect

### ISSUE THREAD

**Issue by andzejsw** [kkazuo/dart-wamp-client#3]
Is there planned `onDisconnect` and `onConnecting` events?
I am rewriting my app from Android to Flutter. And in Android package there was these states. Is there planned something like this?

**Comment by kkazuo** [comment]
There is `onConnect` callback on `WampClient`.
Is it usable?

**Comment by andzejsw** [comment]
> There is `onConnect` callback on `WampClient`.
> Is it usable?

Yes, it is usable. I would like to have also at least `onDisconnect `. For example when by some reason client disconnects, i would be able to call reconnect method.

**Comment by andzejsw** [comment]
I was previously using `Jawampa` on Android.

**Comment by andzejsw** [comment]
Created pull request: https://github.com/kkazuo/dart-wamp-client/pull/6
Inside it i have added `onDisconnect` event.

**Comment by andzejsw** [comment]
Closing, cause merged in master!
